# Generated by Django 5.2.8 on 2025-12-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_remove_perfil_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='ganho_potencial',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='ganho_realizado',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='odd_aposta',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='status',
        ),
        migrations.RemoveField(
            model_name='aposta',
            name='valor_apostado',
        ),
        migrations.AddField(
            model_name='jogo',
            name='xp_valor',
            field=models.IntegerField(default=10, help_text='XP definido pelo admin para este jogo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='xp',
            field=models.IntegerField(default=200),
        ),
    ]
