# Generated by Django 5.2.8 on 2025-12-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0004_remove_aposta_ganho_potencial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='medalhas/')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='medalhas',
            field=models.ManyToManyField(blank=True, related_name='perfis', to='bets.medalha'),
        ),
    ]
